# __Introduction to NumPy__

## __Agenda__

In this lesson, we will cover the following concepts with the help of examples:

- Fundamentals of NumPy
  * Advantages of NumPy
  * NumPy: Installation and Import
- NumPy: Array Object
  * Creating NumPy Arrays

In [ ]:
# Why Numpy ?
x = [[1,2,3],
     [4,5,6]]
print(x)

In [ ]:
x*2 # repetition

In [ ]:
x+x # concatenation

In [ ]:
result=[]
for i in x:
    for j in i:
        result.append(j*2)

In [ ]:
result

In [ ]:
# Flexibility
# Speed

In [ ]:
import numpy as np
a = np.array(x)
a*3

## __1. Fundamentals of NumPy__

NumPy (Numerical Python) is a free and open-source library that is mostly used for mathematical operations in scientific and engineering applications.

- It is a Python library used for working with arrays.
- It consists of a multidimensional array of objects and a collection of functions for manipulating them.
- It conducts mathematical and logical operations on arrays.

**Note:** The array object in NumPy is called ndarray.

### __1.1  Advantages of NumPy__
- It provides an array object that is faster than traditional Python lists.
- It provides supporting functions.
- Arrays are frequently used in data science.
- NumPy arrays are stored in one continuous place in memory, unlike lists.

### __1.2 NumPy: Installation and Import__
- `C:\Users\Your Name>pip install numpy` command is used to install NumPy.
- NumPy is imported under the name np like `import numpy as np`.

## __2. NumPy: Array Object__
A NumPy ndarray object can be created by using the array() function.

In [ ]:
import numpy as np

In [ ]:
np.__version__

In [12]:
# Example:
import numpy as np
arr = np.array ([10,20,30,40,50])
print (arr)
print (type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [13]:
# Example:
import numpy as np
arr = np.array ([10,20,30,40,50,"hello",25.56])
print (arr)
print (type(arr))

['10' '20' '30' '40' '50' 'hello' '25.56']
<class 'numpy.ndarray'>


In [14]:
# coerced to the higher data type
# int < float < complex < string
arr.dtype

dtype('<U32')

In [15]:
# Example:
import numpy as np
arr = np.array ([10,20,30,40,50], dtype='float')
print (arr)
print (type(arr))

[10. 20. 30. 40. 50.]
<class 'numpy.ndarray'>


In [16]:
arr.dtype

dtype('float64')

| Data type	 | Description |
|-------------|-------------|
| `bool_`     | Boolean (True or False) stored as a byte |
| `int_`      | Default integer type (same as C `long`; normally either `int64` or `int32`)| 
| `intc`      | Identical to C `int` (normally `int32` or `int64`)| 
| `intp`      | Integer used for indexing (same as C `ssize_t`; normally either `int32` or `int64`)| 
| `int8`      | Byte (–128 to 127)| 
| `int16`     | Integer (–32768 to 32767)|
| `int32`     | Integer (–2147483648 to 2147483647)|
| `int64`     | Integer (–9223372036854775808 to 9223372036854775807)| 
| `uint8`     | Unsigned integer (0 to 255)| 
| `uint16`    | Unsigned integer (0 to 65535)| 
| `uint32`    | Unsigned integer (0 to 4294967295)| 
| `uint64`    | Unsigned integer (0 to 18446744073709551615)| 
| `float_`    | Shorthand for `float64`| 
| `float16`   | Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| `float32`   | Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| `float64`   | Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| `complex_`  | Shorthand for `complex128`| 
| `complex64` | Complex number, represented by two 32-bit floats| 
| `complex128`| Complex number, represented by two 64-bit floats| 

In [17]:
# Example:
import numpy as np
arr = np.array ([10,20,30,40,50], dtype='int8')
print (arr)
print (type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [18]:
arr.dtype

dtype('int8')

In [19]:
# another way
# Example:
import numpy as np
arr = np.array ([10,20,30,40,50], dtype=np.int32)
print (arr)
print (type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [20]:
arr.dtype

dtype('int32')

### __2.1 Creating NumPy Arrays__
- Create multiple dimensional arrays, such as 0D, 1D, 2D and 3D

In [21]:
# Create a 0D Array
arr0 = np.array(24)
print ('0D array is', arr0)
# Create a 1D Array
arr1 = np.array([1,2,3,4])
print ('1D array is', arr1)
# Create a 2D Array
arr2 = np.array([[1,1,1],[1,2,1]])
print ('2D array is', arr2)
# Create a 3D Array
arr3 = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
print ('3D array is', arr3)

0D array is 24
1D array is [1 2 3 4]
2D array is [[1 1 1]
 [1 2 1]]
3D array is [[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]


**Observations:**
- 1D arrays are unidimensional and have 0D arrays as its elements.
- 2D arrays have 1D arrays as their elements.
- 3D arrays have 2D arrays as their elements.

In [22]:
arr0.ndim # number of dimensions

0

In [23]:
arr1.ndim, arr2.ndim, arr3.ndim

(1, 2, 3)

In [24]:
arr2.shape 

(2, 3)

In [25]:
arr2

array([[1, 1, 1],
       [1, 2, 1]])

In [26]:
arr3.shape

(2, 2, 3)

## __Assisted Practice__

### __Problem Statement:__

Create the following NumPy arrays and print them using appropriate code:

- A 0D array (scalar)

- A 1D array with elements [1, 2, 3, 4]

- A 2D array with elements [[1, 1, 1], [1, 2, 1]]

- A 3D array with elements [[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]]

In [ ]:
# create array, display type, shape, ndim, dtype